version: '3'

services:
  minio:
    image: minio/minio:latest
    ports:
      - "${MINIO_PORT_HOST:?}:9000"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:?}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:?}
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MINIO_PORT_HOST:?}/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  
  id_service:
    build:
      context: ../../uid/
      dockerfile: Dockerfile
    image: id_service
    ports:
      - "5003:5003"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:?}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:?}
      MINIO_URL: minio:9000

  flaskapp:
    build:
      context: ..
      # TODO: 2020/07/01, Elvis - With gunicorn's execution issue resolved, consider removing 'Dockerfile-flask'
      dockerfile: Dockerfile
    image: flask_app
    ports:
      - "5001:5001"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:?}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:?}
      MINIO_URL: minio:9000
      UID_VALIDATE_URL: http://id_service:5003/api/uid/validate
